"""Constants module for the RICKD analysis project."""

RICKD_ROOT_DATA_FOLDER = "/Users/adrianzapaterreig/Documents/Personal/TFM/data/Running Injury Clinic Kinematic Dataset"
RICKD_SOURCE_DATA_FOLDER = f"{RICKD_ROOT_DATA_FOLDER}/source_data"
RICKD_PROCESSED_DATA_FOLDER = f"{RICKD_ROOT_DATA_FOLDER}/processed_data"
RICKD_RESULTS_FOLDER = f"{RICKD_ROOT_DATA_FOLDER}/results"
RICKD_PROY_RESOURCE_FOLDER = "/Users/adrianzapaterreig/Documents/Personal/TFM/rickd-analysis/resources"

# MATLAB output data
RICKD_MATLAB_OUTPUT_FOLDER = f"{RICKD_PROCESSED_DATA_FOLDER}/matlab_output"

# Processed data files
RICKD_RUNNING_METADATA_FILE = f"{RICKD_ROOT_DATA_FOLDER}/run_data_meta.csv"
RICKD_RUNNING_METADATA_CLEANED_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/run_data_meta_cleaned.csv"
RICKD_DESCRIPTIVE_VARIABLES_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/descriptive_variables.csv"
RICKD_MARKER_CENTERS_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/marker_centers.csv"
RICKD_MARKER_DATA_120HZ_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/marker_data_120hz.csv"
RICKD_MARKER_DATA_200HZ_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/marker_data_200hz.csv"
RICKD_SESSION_DATA_FULL_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/session_data_full.csv"
RICKD_SESSION_DATA_FULL_CLEANED_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/session_data_full_cleaned.csv"
RICKD_FEATURE_SELECTION_DATA_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/feature_selection_data.csv"
RICKD_FEATURE_SELECTION_PART_2_DATA_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/feature_selection_data_part_2.csv"

# Test Train sets:
# Baseline - failed
RICKD_BASELINE_X_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/baseline_X.csv"
RICKD_BASELINE_Y_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/baseline_Y.csv"
RICKD_BASELINE_X_TRAIN_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/baseline_X_train.csv"
RICKD_BASELINE_X_TEST_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/baseline_X_test.csv"
RICKD_BASELINE_Y_TRAIN_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/baseline_y_train.csv"
RICKD_BASELINE_Y_TEST_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/baseline_y_test.csv"
# Clasical ML model selection
RICKD_MODEL_1_X_TRAIN_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/model_1_X_train.csv"
RICKD_MODEL_1_X_TEST_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/model_1_X_test.csv"
RICKD_MODEL_1_Y_TRAIN_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/model_1_y_train.csv"
RICKD_MODEL_1_Y_TEST_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/model_1_y_test.csv"
# Preprocessed
RICKD_MODEL_1_X_TRAIN_PREPROCESSED_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/model_1_X_train_preprocessed.csv"
RICKD_MODEL_1_X_TEST_PREPROCESSED_FILE = f"{RICKD_PROCESSED_DATA_FOLDER}/model_1_X_test_preprocessed.csv"
# Selected 40 features
RICKD_MODEL_1_X_TRAIN_FILE_40_FEATURES = f"{RICKD_PROCESSED_DATA_FOLDER}/model_1_X_train_40_features.csv"
RICKD_MODEL_1_X_TEST_FILE_40_FEATURES = f"{RICKD_PROCESSED_DATA_FOLDER}/model_1_X_test_40_features.csv"

# Mapping files
RICKD_MAP_INJURY_CODE = f"{RICKD_PROY_RESOURCE_FOLDER}/injury_code_mapping.csv"
RICKD_MAP_INJURY_DESC = f"{RICKD_PROY_RESOURCE_FOLDER}/injury_desc_mapping.csv"
RICKD_MAP_SELF_INJURY_CODE = f"{RICKD_PROY_RESOURCE_FOLDER}/self_select_injury_code_mapping.csv"
RICKD_MAP_INJURED_JOINT = f"{RICKD_PROY_RESOURCE_FOLDER}/injured_joint_mapping.csv"
RICKD_MAP_INJURED_JOINT_SIDE = f"{RICKD_PROY_RESOURCE_FOLDER}/injured_joint_side_mapping.csv"


# Models
RICKD_MODELS_FOLDER = f"{RICKD_RESULTS_FOLDER}/models"
# Baseline - failed
RICKD_BASELINE_RESULTS_FOLDER = f"{RICKD_MODELS_FOLDER}/baselineV2"
RICKD_BASELINE_RESULTS_SUMMARY_FILE = f"{RICKD_BASELINE_RESULTS_FOLDER}/results_summary.json"
# Model 1
RICKD_MODEL_1_RESULTS_FOLDER = f"{RICKD_MODELS_FOLDER}/model_1"
RICKD_MODEL_1_RESULTS_SUMMARY_FILE = f"{RICKD_MODEL_1_RESULTS_FOLDER}/results_summary.json"
