"""This module provides functionality to load and access CSV data generated by MATLAB 

The data structure follows the MATLAB processing output format with:
- Root level: processing_summary.csv and session_discrete_variables.csv
- Session level: {ID}/ folders containing inputs/ and results/ subfolders
"""

import pandas as pd
from pathlib import Path
from typing import Dict, List, Tuple, Optional
import warnings
import kineticstoolkit as ktk
 
from .constants import RICKD_MATLAB_OUTPUT_FOLDER
from .constants import RICKD_SESSION_DATA_FULL_CLEANED_FILE

# File name constants
PROCESSING_SUMMARY_FILE_NAME = "processing_summary.csv"
DISCRETE_VARIABLES_FILE_NAME = "session_discrete_variables.csv"
GAIT_CYCLE_EVENTS_FILE_NAME = "gait_cycle_events.csv"
JOINT_CENTERS_FILE_NAME = "joint_centers.csv"

# Folder name constants
RESULTS_FOLDER_NAME = "results"
INPUTS_FOLDER_NAME = "inputs"

# File suffix constants
ANGLES_SUFFIX = "_angles.csv"
VELOCITIES_SUFFIX = "_velocities.csv"
NORM_ANGLES_SUFFIX = "_norm_angles.csv"
NORM_VELOCITIES_SUFFIX = "_norm_velocities.csv"
MARKER_DATA_SUFFIX = "_marker_data.csv"
MATLAB_RESULTS_FILE_SUFFIX = "_matlab_results.mat"

# File name templates
JOINT_ANGLES_TEMPLATE = "{joint}" + ANGLES_SUFFIX
JOINT_NORM_ANGLES_TEMPLATE = "{joint}" + NORM_ANGLES_SUFFIX
JOINT_VELOCITIES_TEMPLATE = "{joint}" + VELOCITIES_SUFFIX
JOINT_NORM_VELOCITIES_TEMPLATE = "{joint}" + NORM_VELOCITIES_SUFFIX
MARKER_DATA_TEMPLATE = "{marker}" + MARKER_DATA_SUFFIX


class MatlabDataLoader:
    """
    Loader for MATLAB-processed gait analysis data.

    This class provides methods to load:
    1. Individual session data (joint angles, velocities, etc.)
    2. Aggregate data (processing summary, discrete variables)

    The data structure follows the MATLAB output format described in the documentation.
    """

    def __init__(self, matlab_output_folder: str = RICKD_MATLAB_OUTPUT_FOLDER):
        """
        Initialize the data loader.

        Args:
            matlab_output_folder: Path to the MATLAB output folder containing processed data
        """
        self.matlab_output_folder: Path = Path(matlab_output_folder)

        # TODO: Add RICKD_SESSION_DATA_FULL_CLEANED_FILE to data loader
        # TODO: consolidate session_data_full_cleaned.csv file with discrete_variables by performing an inner join by ID and selecting, via a list, the columns to keep from each side.
        # TODO: Add is_healthy status to discrete variables and metadata file. -> logic injury_code == "no_injury"
        # TODO: Add info like HZ, Age, Health status to TimeSeries object that are returned. i.e. ts.add_data_info("Metadata", "Hz", "200")

        if not self.matlab_output_folder.exists():
            raise FileNotFoundError(f"MATLAB output folder not found: {matlab_output_folder}")

        # Cache for loaded data to avoid repeated file reads
        self._processing_summary_cache: pd.DataFrame | None = None
        self._discrete_variables_cache: pd.DataFrame | None = None
        self._session_data_full_cleaned_cache: pd.DataFrame | None = None
        # Cache for consolidated discrete + metadata join
        self._discrete_with_metadata_cache: pd.DataFrame | None = None

    def get_processing_summary(self, refresh_cache: bool = False) -> pd.DataFrame:
        """
        Load the processing summary containing status for all processed files.

        Args:
            refresh_cache: Whether to reload the data from file

        Returns:
            DataFrame with columns: FileIndex, ID, SubjectID, SessionID, 
                                  JsonFile, ProcessingStatus, ErrorMessage
        """
        if self._processing_summary_cache is None or refresh_cache:
            summary_file = self.matlab_output_folder / PROCESSING_SUMMARY_FILE_NAME
            if not summary_file.exists():
                raise FileNotFoundError(f"Processing summary file not found: {summary_file}")

            self._processing_summary_cache = pd.read_csv(summary_file)

        return self._processing_summary_cache.copy()

    def get_discrete_variables(self, refresh_cache: bool = False) -> pd.DataFrame:
        """
        Load the discrete variables data for all successfully processed sessions.

        Args:
            refresh_cache: Whether to reload the data from file

        Returns:
            DataFrame with discrete gait variables for each session
        """
        if self._discrete_variables_cache is None or refresh_cache:
            discrete_file = self.matlab_output_folder / DISCRETE_VARIABLES_FILE_NAME
            if not discrete_file.exists():
                raise FileNotFoundError(f"Discrete variables file not found: {discrete_file}")

            self._discrete_variables_cache = pd.read_csv(discrete_file)

        return self._discrete_variables_cache.copy()

    # New: Load cleaned session metadata file
    def get_session_data_full_cleaned(self, refresh_cache: bool = False) -> pd.DataFrame:
        """
        Load the cleaned session metadata file (subject/session demographics and injury info).

        Returns:
            DataFrame with columns like: id, sub_id, age, Gender, injury_code, ... and is_injured column.
        """
        
        if self._session_data_full_cleaned_cache is None or refresh_cache:
            metadata_path = Path(RICKD_SESSION_DATA_FULL_CLEANED_FILE)
            if not metadata_path.exists():
                raise FileNotFoundError(
                    f"Cleaned session data file not found: {metadata_path}. "
                    "Generate it first or set the correct path in constants."
                )
            df_meta = pd.read_csv(metadata_path)
            self._session_data_full_cleaned_cache = df_meta
        return self._session_data_full_cleaned_cache.copy()


    def get_discrete_with_metadata(
        self,
        columns_from_discrete: Optional[List[str]] = None,
        columns_from_metadata: Optional[List[str]] = None,
        refresh_cache: bool = False,
    ) -> pd.DataFrame:
        """
        Return an inner-joined DataFrame between discrete variables and cleaned session metadata.

        Args:
            columns_from_discrete: Subset of discrete variables columns to keep (default keeps all)
            columns_from_metadata: Subset of metadata columns to keep from the cleaned file (default keeps useful subset)
            refresh_cache: Whether to refresh caches for both sources

        Returns:
            Joined DataFrame on session identifier (discrete.ID == metadata.id) containing selected columns and an is_healthy flag.
        """
        if self._discrete_with_metadata_cache is None or refresh_cache:
            d_full = self.get_discrete_variables(refresh_cache=refresh_cache)
            m_full = self.get_session_data_full_cleaned(refresh_cache=refresh_cache)
            if 'ID' not in d_full.columns:
                raise KeyError("Expected column 'ID' in discrete variables for joining.")
            if 'id' not in m_full.columns:
                raise KeyError("Expected column 'id' in metadata for joining.")
            
            # Fail if column conflict. TODO: Handle edge case...
            self._discrete_with_metadata_cache = d_full.merge(m_full, left_on='ID', right_on='id', how='inner', suffixes=(False, False))

        joined_full = self._discrete_with_metadata_cache

        selected_cols: List[str] = []
        if columns_from_discrete is None:
            d_cols = [c for c in self.get_discrete_variables().columns if c in joined_full.columns]
            selected_cols.extend(d_cols)
        else:
            missing = [c for c in columns_from_discrete if c not in joined_full.columns]
            if missing:
                warnings.warn(f"Some requested discrete columns are missing and will be ignored: {missing}")
            selected_cols.extend([c for c in columns_from_discrete if c in joined_full.columns])

        if columns_from_metadata is None:
            meta_cols = [c for c in self.get_session_data_full_cleaned().columns if c in joined_full.columns]
            selected_cols.extend(meta_cols)
        else:
            missing = [c for c in columns_from_metadata if c not in joined_full.columns]
            if missing:
                warnings.warn(f"Some requested metadata columns are missing and will be ignored: {missing}")
            selected_cols.extend([c for c in columns_from_metadata if c in joined_full.columns])

        # Deduplicate while preserving order
        seen = set()
        ordered_cols = [c for c in selected_cols if not (c in seen or seen.add(c))]
        return joined_full.loc[:, ordered_cols]

    def get_available_sessions(self) -> List[str]:
        """
        Get list of all available session IDs that have processed data.

        NOTE: Looks at the folder structure to find all available sessions.
        It is prefered to use get_successful_sessions() instead.

        Returns:
            List of session IDs (format: {subject_id}_{session_id})
        """
        sessions = []
        for item in self.matlab_output_folder.iterdir():
            if item.is_dir() and not item.name.startswith('.'):
                # Check if it has the expected structure (inputs and results folders)
                if (item / INPUTS_FOLDER_NAME).exists() and (item / RESULTS_FOLDER_NAME).exists():
                    sessions.append(item.name)

        return sorted(sessions)

    def get_successful_sessions(self) -> List[str]:
        """
        Get list of session IDs that were successfully processed.

        Returns:
            List of successfully processed session IDs
        """
        summary = self.get_processing_summary()
        successful = summary[summary['ProcessingStatus'] == 'Success']
        return successful['ID'].tolist()

    def get_failed_sessions(self) -> List[Tuple[str, str]]:
        """
        Get list of session IDs that failed processing along with error messages.

        Returns:
            List of tuples (session_id, error_message)
        """
        summary = self.get_processing_summary()
        failed = summary[summary['ProcessingStatus'] == 'Error']
        return list(zip(failed['ID'].tolist(), failed['ErrorMessage'].tolist()))

    def get_session_folder(self, session_id: str) -> Path:
        """
        Get the path to a specific session's data folder.

        Args:
            session_id: Session identifier (format: {subject_id}_{session_id})

        Returns:
            Path to the session folder

        Raises:
            FileNotFoundError: If session folder doesn't exist
        """
        session_folder = self.matlab_output_folder / session_id
        if not session_folder.exists():
            raise FileNotFoundError(f"Session folder not found: {session_folder}")

        return session_folder

    def get_joint_angles(self, session_id: str, joint: str, 
                        normalized: bool = False) -> pd.DataFrame:
        """
        Load joint angle data for a specific session and joint.

        Args:
            session_id: Session identifier
            joint: Joint name (e.g., 'L_ankle', 'R_knee', 'pelvis')
            normalized: Whether to load normalized (% gait cycle) or raw time series data

        Returns:
            DataFrame with angle data:
            - If normalized=False: columns are TimeIndex, X_deg, Y_deg, Z_deg
            - If normalized=True: columns are PercentGaitCycle, X_deg, Y_deg, Z_deg
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME

        if normalized:
            filename = JOINT_NORM_ANGLES_TEMPLATE.format(joint=joint)
        else:
            filename = JOINT_ANGLES_TEMPLATE.format(joint=joint)

        file_path = results_folder / filename
        if not file_path.exists():
            raise FileNotFoundError(f"Joint angles file not found: {file_path}")

        return pd.read_csv(file_path)

    def get_joint_velocities(self, session_id: str, joint: str, 
                           normalized: bool = False) -> pd.DataFrame:
        """
        Load joint velocity data for a specific session and joint.

        Args:
            session_id: Session identifier
            joint: Joint name (e.g., 'L_ankle', 'R_knee', 'pelvis')
            normalized: Whether to load normalized (% gait cycle) or raw time series data

        Returns:
            DataFrame with velocity data:
            - If normalized=False: columns are TimeIndex, X_deg_per_s, Y_deg_per_s, Z_deg_per_s
            - If normalized=True: columns are PercentGaitCycle, X_deg_per_s, Y_deg_per_s, Z_deg_per_s
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME

        if normalized:
            filename = JOINT_NORM_VELOCITIES_TEMPLATE.format(joint=joint)
        else:
            filename = JOINT_VELOCITIES_TEMPLATE.format(joint=joint)

        file_path = results_folder / filename
        if not file_path.exists():
            raise FileNotFoundError(f"Joint velocities file not found: {file_path}")

        return pd.read_csv(file_path)

    def get_all_joint_angles(self, session_id: str, normalized: bool = False) -> Dict[str, pd.DataFrame]:
        """
        Load angle data for all joints in a session.

        Args:
            session_id: Session identifier
            normalized: Whether to load normalized or raw data

        Returns:
            Dictionary mapping joint names to their angle DataFrames
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME

        joint_data = {}
        suffix = NORM_ANGLES_SUFFIX if normalized else ANGLES_SUFFIX

        for file_path in results_folder.glob(f"*{ANGLES_SUFFIX}"):
            # Handle both _angles.csv and _norm_angles.csv
            file_name = file_path.name
            if file_name.endswith(NORM_ANGLES_SUFFIX):
                if normalized:
                    joint_name = file_name.replace(NORM_ANGLES_SUFFIX, "")
                    joint_data[joint_name] = pd.read_csv(file_path)
            elif file_name.endswith(ANGLES_SUFFIX):
                if not normalized:
                    joint_name = file_name.replace(ANGLES_SUFFIX, "")
                    joint_data[joint_name] = pd.read_csv(file_path)

        return joint_data

    def get_all_joint_velocities(self, session_id: str, normalized: bool = False) -> Dict[str, pd.DataFrame]:
        """
        Load velocity data for all joints in a session.

        Args:
            session_id: Session identifier
            normalized: Whether to load normalized or raw data

        Returns:
            Dictionary mapping joint names to their velocity DataFrames
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME

        joint_data = {}

        for file_path in results_folder.glob(f"*{VELOCITIES_SUFFIX}"):
            # Handle both _velocities.csv and _norm_velocities.csv
            file_name = file_path.name
            if file_name.endswith(NORM_VELOCITIES_SUFFIX):
                if normalized:
                    joint_name = file_name.replace(NORM_VELOCITIES_SUFFIX, "")
                    joint_data[joint_name] = pd.read_csv(file_path)
            elif file_name.endswith(VELOCITIES_SUFFIX):
                if not normalized:
                    joint_name = file_name.replace(VELOCITIES_SUFFIX, "")
                    joint_data[joint_name] = pd.read_csv(file_path)

        return joint_data

    def get_gait_events(self, session_id: str) -> pd.DataFrame:
        """
        Load gait cycle events for a session.

        Args:
            session_id: Session identifier

        Returns:
            DataFrame with gait events with meaningful column names:
            - EventNumber: Gait cycle number
            - L_TD: Left touchdown frame index
            - L_Midstance: Left midstance frame index
            - L_TO: Left toe-off frame index
            - L_heelwhip: Left maximum heel whip during swing frame index
            - R_TD: Right touchdown frame index
            - R_Midstance: Right midstance frame index
            - R_TO: Right toe-off frame index
            - R_heelwhip: Right maximum heel whip during swing frame index
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME
        events_file = results_folder / GAIT_CYCLE_EVENTS_FILE_NAME

        if not events_file.exists():
            raise FileNotFoundError(f"Gait events file not found: {events_file}")

        df = pd.read_csv(events_file)

        # Rename columns to meaningful event names based on the extended event matrix
        # From documentation: [L_TD, L_Midstance, L_TO, L_heelwhip, R_TD, R_Midstance, R_TO, R_heelwhip]
        event_column_mapping = {
            'EventIndex_1': 'L_TD',
            'EventIndex_2': 'L_Midstance', 
            'EventIndex_3': 'L_TO',
            'EventIndex_4': 'L_heelwhip',
            'EventIndex_5': 'R_TD',
            'EventIndex_6': 'R_Midstance',
            'EventIndex_7': 'R_TO',
            'EventIndex_8': 'R_heelwhip'
        }

        df = df.rename(columns=event_column_mapping)

        return df

    def get_joint_centers(self, session_id: str) -> pd.DataFrame:
        """
        Load joint center coordinates for a session.

        Args:
            session_id: Session identifier

        Returns:
            DataFrame with joint centers (Joint, X_coord, Y_coord, Z_coord)
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME
        centers_file = results_folder / JOINT_CENTERS_FILE_NAME

        if not centers_file.exists():
            raise FileNotFoundError(f"Joint centers file not found: {centers_file}")

        return pd.read_csv(centers_file)

    def get_marker_data(self, session_id: str, marker: str) -> pd.DataFrame:
        """
        Load marker trajectory data for a specific marker.

        Args:
            session_id: Session identifier
            marker: Marker name (e.g., 'L_foot_1', 'R_thigh_2', 'pelvis_3')

        Returns:
            DataFrame with marker trajectory (TimeIndex, X_coord, Y_coord, Z_coord)
        """
        session_folder = self.get_session_folder(session_id)
        inputs_folder = session_folder / INPUTS_FOLDER_NAME
        marker_file = inputs_folder / MARKER_DATA_TEMPLATE.format(marker=marker)

        if not marker_file.exists():
            raise FileNotFoundError(f"Marker data file not found: {marker_file}")

        return pd.read_csv(marker_file)

    def get_available_joints(self, session_id: str) -> List[str]:
        """
        Get list of available joints for a session.

        Args:
            session_id: Session identifier

        Returns:
            List of joint names available in this session
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME

        joints = set()
        for file_path in results_folder.glob(f"*{ANGLES_SUFFIX}"):
            # Handle both _angles.csv and _norm_angles.csv
            file_name = file_path.name
            if file_name.endswith(NORM_ANGLES_SUFFIX):
                joint_name = file_name.replace(NORM_ANGLES_SUFFIX, "")
            elif file_name.endswith(ANGLES_SUFFIX):
                joint_name = file_name.replace(ANGLES_SUFFIX, "")
            else:
                continue  # Skip files that don't match expected pattern
            joints.add(joint_name)

        return sorted(list(joints))

    def get_available_markers(self, session_id: str) -> List[str]:
        """
        Get list of available markers for a session.

        Args:
            session_id: Session identifier

        Returns:
            List of marker names available in this session
        """
        session_folder = self.get_session_folder(session_id)
        inputs_folder = session_folder / INPUTS_FOLDER_NAME

        markers = set()
        for file_path in inputs_folder.glob(f"*{MARKER_DATA_SUFFIX}"):
            marker_name = file_path.name.replace(MARKER_DATA_SUFFIX, "")
            markers.add(marker_name)

        return sorted(markers)

    def get_session_info(self, session_id: str) -> Dict:
        """
        Get comprehensive information about a session.

        Args:
            session_id: Session identifier

        Returns:
            Dictionary with session information including available data types
        """
        session_folder = self.get_session_folder(session_id)

        info = {
            'session_id': session_id,
            'folder_path': str(session_folder),
            'available_joints': self.get_available_joints(session_id),
            'available_markers': self.get_available_markers(session_id),
            'has_gait_events': (session_folder / RESULTS_FOLDER_NAME / GAIT_CYCLE_EVENTS_FILE_NAME).exists(),
            'has_joint_centers': (session_folder / RESULTS_FOLDER_NAME / JOINT_CENTERS_FILE_NAME).exists(),
            'has_matlab_results': (session_folder / f"{session_id}{MATLAB_RESULTS_FILE_SUFFIX}").exists()
        }

        # Add processing status if available
        try:
            summary = self.get_processing_summary()
            session_info = summary[summary['ID'] == session_id]
            if not session_info.empty:
                info['processing_status'] = session_info.iloc[0]['ProcessingStatus']
                info['subject_id'] = session_info.iloc[0]['SubjectID']
                info['session_id_only'] = session_info.iloc[0]['SessionID']
        except Exception as e:
            warnings.warn(f"Could not load processing summary: {e}")

        return info

    # Internal: build a metadata dict for a session
    def _get_session_metadata(self, session_id: str) -> Dict[str, Optional[str]]:
        metadata: Dict[str, Optional[str]] = {'session_id': session_id}
        # From discrete variables
        try:
            discrete_df = self.get_discrete_variables()
            row_d = discrete_df.loc[discrete_df['ID'] == session_id]
            if not row_d.empty:
                r = row_d.iloc[0]
                metadata['subject_id'] = r.get('sub_id', None)
                metadata['hz'] = r.get('Hz', None)
                metadata['speed'] = r.get('Speed_Output', None)
            else:
                raise ValueError(f"Session {session_id} not found in discrete_variables")
        except Exception as e:
            warnings.warn(f"Could not load discrete_variables for ts metadata: {e}")
            pass
        # From cleaned metadata
        try:
            meta_df = self.get_session_data_full_cleaned()
            row_m = meta_df.loc[meta_df['id'] == session_id]
            if not row_m.empty:
                r = row_m.iloc[0]
                metadata['age'] = r.get('age', None)
                metadata['gender'] = r.get('Gender', None)
                metadata['height'] = r.get('Height', None)
                metadata['weight'] = r.get('Weight', None)
                metadata['dominant_leg'] = r.get('DominantLeg', None)
                metadata['injury_code'] = r.get('injury_code', None)
                metadata['injured_side_code'] = r.get('injured_side_code', None)
                metadata['injury_severity_code'] = r.get('injury_severity_code', None)
                metadata['injured_joint_code'] = r.get('injured_joint_code', None)
            else:
                raise ValueError(f"Session {session_id} not found in session_data_full_cleaned")
        except Exception as e:
            warnings.warn(f"Could not load session_data_full_cleaned for ts metadata: {e}")
            pass
        return metadata

    # Internal: attach metadata to a TimeSeries in a safe way
    def _add_metadata_to_timeseries(self, ts: ktk.TimeSeries, session_id: str) -> ktk.TimeSeries:
        meta = self._get_session_metadata(session_id)
        for key, val in meta.items():
            if val is None:
                continue
            # Store as string for compatibility
            try:
                ts = ts.add_data_info("Metadata", key, str(val))
            except Exception as e:
                warnings.warn(f"Could not add metadata to TimeSeries: {e}")
                pass
        return ts

    def get_joint_angles_timeseries(self, session_id: str, joint: str, 
                                   normalized: bool = False, 
                                   include_events: bool = False) -> ktk.TimeSeries:
        """
        Load joint angle data as a ktk.TimeSeries object.

        Args:
            session_id: Session identifier
            joint: Joint name (e.g., 'L_ankle', 'R_knee', 'pelvis')
            normalized: Whether to load normalized (% gait cycle) or raw time series data
            include_events: Whether to include gait events (only for unnormalized data)

        Returns:
            ktk.TimeSeries object with angle data
        """
        df = self.get_joint_angles(session_id, joint, normalized)

        ts = ktk.TimeSeries()

        if normalized:
            ts.time = df["PercentGaitCycle"]
            ts = ts.add_data(f"{joint}_angle", df[["X_deg", "Y_deg", "Z_deg"]].values)
        else:
            ts.time = df["TimeIndex"]
            ts = ts.add_data(f"{joint}_angle", df[["X_deg", "Y_deg", "Z_deg"]].values)

            if include_events:
                events_df = self.get_gait_events(session_id)
                if joint.startswith('L_'):
                    event_names = ['L_TD', 'L_TO']
                elif joint.startswith('R_'):
                    event_names = ['R_TD', 'R_TO']
                else:
                    # For bilateral or unspecified joints, add all events i.e. pelvis
                    event_names = ['L_TD', 'L_TO', 'R_TD', 'R_TO']

                # Add relevant events
                for _, event_row in events_df.iterrows():
                    for event_name in event_names:
                        if not pd.isna(event_row[event_name]):
                            ts = ts.add_event(event_row[event_name], event_name)

        # Enrich with metadata
        ts = self._add_metadata_to_timeseries(ts, session_id)
        return ts

    def get_joint_velocities_timeseries(self, session_id: str, joint: str, 
                                       normalized: bool = False,
                                       include_events: bool = False) -> ktk.TimeSeries:
        """
        Load joint velocity data as a ktk.TimeSeries object.

        Args:
            session_id: Session identifier
            joint: Joint name (e.g., 'L_ankle', 'R_knee', 'pelvis')
            normalized: Whether to load normalized (% gait cycle) or raw time series data
            include_events: Whether to include gait events (only for unnormalized data)

        Returns:
            ktk.TimeSeries object with velocity data
        """
        df = self.get_joint_velocities(session_id, joint, normalized)

        ts = ktk.TimeSeries()

        if normalized:
            ts.time = df["PercentGaitCycle"]
            ts = ts.add_data(f"{joint}_velocity", df[["X_deg_per_s", "Y_deg_per_s", "Z_deg_per_s"]].values)
        else:
            ts.time = df["TimeIndex"]
            ts = ts.add_data(f"{joint}_velocity", df[["X_deg_per_s", "Y_deg_per_s", "Z_deg_per_s"]].values)

            if include_events:
                events_df = self.get_gait_events(session_id)
                if joint.startswith('L_'):
                    event_names = ['L_TD', 'L_TO']
                elif joint.startswith('R_'):
                    event_names = ['R_TD', 'R_TO']
                else:
                    event_names = ['L_TD', 'L_TO', 'R_TD', 'R_TO']

                for _, event_row in events_df.iterrows():
                    for event_name in event_names:
                        if not pd.isna(event_row[event_name]):
                            ts = ts.add_event(event_row[event_name], event_name)

        # Enrich with metadata
        ts = self._add_metadata_to_timeseries(ts, session_id)
        return ts

    def get_marker_data_timeseries(self, session_id: str, marker: str,
                                  include_events: bool = False) -> ktk.TimeSeries:
        """
        Load marker trajectory data as a ktk.TimeSeries object.

        Args:
            session_id: Session identifier
            marker: Marker name (e.g., 'L_foot_1', 'R_thigh_2', 'pelvis_3')
            include_events: Whether to include gait events

        Returns:
            ktk.TimeSeries object with marker trajectory data
        """
        df = self.get_marker_data(session_id, marker)

        ts = ktk.TimeSeries()
        ts.time = df["TimeIndex"]
        ts = ts.add_data(f"{marker}_trajectory", df[["X_coord", "Y_coord", "Z_coord"]].values)

        if include_events:
            events_df = self.get_gait_events(session_id)
            if marker.startswith('L_'):
                event_names = ['L_TD', 'L_TO']
            elif marker.startswith('R_'):
                event_names = ['R_TD', 'R_TO']
            else:
                event_names = ['L_TD', 'L_TO', 'R_TD', 'R_TO']

            for _, event_row in events_df.iterrows():
                for event_name in event_names:
                    if not pd.isna(event_row[event_name]):
                        ts = ts.add_event(event_row[event_name], event_name)

        # Enrich with metadata
        ts = self._add_metadata_to_timeseries(ts, session_id)
        return ts

    def get_all_joint_angles_timeseries(self, session_id: str, normalized: bool = False,
                                       include_events: bool = False) -> Dict[str, ktk.TimeSeries]:
        """
        Load angle data for all joints as ktk.TimeSeries objects.

        Args:
            session_id: Session identifier
            normalized: Whether to load normalized or raw data
            include_events: Whether to include gait events (only for unnormalized data)

        Returns:
            Dictionary mapping joint names to their ktk.TimeSeries objects
        """
        joint_timeseries = {}
        available_joints = self.get_available_joints(session_id)

        for joint in available_joints:
            try:
                joint_timeseries[joint] = self.get_joint_angles_timeseries(
                    session_id, joint, normalized, include_events
                )
            except FileNotFoundError as e:
                # Note: There is joint discrepancies between the raw and normalized data
                # TODO: Add normalized flag to get_available_joints
                word = "normalized " if normalized else ""
                warnings.warn(f"Could not load TimeSeries for {word}joint {joint}: {e}")

        return joint_timeseries

    def get_all_joint_velocities_timeseries(self, session_id: str, normalized: bool = False,
                                           include_events: bool = False) -> Dict[str, ktk.TimeSeries]:
        """
        Load velocity data for all joints as ktk.TimeSeries objects.

        Args:
            session_id: Session identifier
            normalized: Whether to load normalized or raw data
            include_events: Whether to include gait events (only for unnormalized data)

        Returns:
            Dictionary mapping joint names to their ktk.TimeSeries objects
        """
        joint_timeseries = {}
        available_joints = self.get_available_joints(session_id)

        for joint in available_joints:
            try:
                joint_timeseries[joint] = self.get_joint_velocities_timeseries(
                    session_id, joint, normalized, include_events
                )
            except FileNotFoundError as e:
                warnings.warn(f"Could not load TimeSeries for joint {joint}: {e}")

        return joint_timeseries


def segment_ts_by_stance_phase(ts: ktk.TimeSeries, side: str) -> List[ktk.TimeSeries]:
    """
    Segment a TimeSeries object into stance phases based on touchdown and toe-off events.

    Args:
        ts: The TimeSeries object to segment
        side: Side of the joint ('L' or 'R')

    Returns:
        List of TimeSeries objects, one for each stance phase
    """
    # Find touchdown and toe-off events for the specified side
    td_name = f"{side}_TD"
    to_name = f"{side}_TO"

    # Extract event times (as indices) for touchdown and toe-off
    td_count = [1 for event in ts.events if event.name == td_name]

    stance_segments = []
    for i in range(len(td_count)):
        segment = ts.get_ts_between_events(td_name, to_name, i, i, inclusive=True)
        segment = segment.trim_events()
        stance_segments.append(segment)

    return stance_segments

