"""This module provides functionality to load and access CSV data generated by MATLAB 

The data structure follows the MATLAB processing output format with:
- Root level: processing_summary.csv and session_discrete_variables.csv
- Session level: {ID}/ folders containing inputs/ and results/ subfolders
"""

import pandas as pd
from pathlib import Path
from typing import Dict, List, Tuple, Optional
import warnings
import numpy as np
import kineticstoolkit as ktk
 
from .constants import RICKD_MATLAB_OUTPUT_FOLDER

# File name constants
PROCESSING_SUMMARY_FILE_NAME = "processing_summary.csv"
DISCRETE_VARIABLES_FILE_NAME = "session_discrete_variables.csv"
GAIT_CYCLE_EVENTS_FILE_NAME = "gait_cycle_events.csv"
JOINT_CENTERS_FILE_NAME = "joint_centers.csv"

# Folder name constants
RESULTS_FOLDER_NAME = "results"
INPUTS_FOLDER_NAME = "inputs"

# File suffix constants
ANGLES_SUFFIX = "_angles.csv"
VELOCITIES_SUFFIX = "_velocities.csv"
NORM_ANGLES_SUFFIX = "_norm_angles.csv"
NORM_VELOCITIES_SUFFIX = "_norm_velocities.csv"
MARKER_DATA_SUFFIX = "_marker_data.csv"
MATLAB_RESULTS_FILE_SUFFIX = "_matlab_results.mat"

# File name templates
JOINT_ANGLES_TEMPLATE = "{joint}" + ANGLES_SUFFIX
JOINT_NORM_ANGLES_TEMPLATE = "{joint}" + NORM_ANGLES_SUFFIX
JOINT_VELOCITIES_TEMPLATE = "{joint}" + VELOCITIES_SUFFIX
JOINT_NORM_VELOCITIES_TEMPLATE = "{joint}" + NORM_VELOCITIES_SUFFIX
MARKER_DATA_TEMPLATE = "{marker}" + MARKER_DATA_SUFFIX


class MatlabDataLoader:
    """
    Loader for MATLAB-processed gait analysis data.
    
    This class provides methods to load:
    1. Individual session data (joint angles, velocities, etc.)
    2. Aggregate data (processing summary, discrete variables)
    
    The data structure follows the MATLAB output format described in the documentation.
    """

    def __init__(self, matlab_output_folder: str = RICKD_MATLAB_OUTPUT_FOLDER):
        """
        Initialize the data loader.
        
        Args:
            matlab_output_folder: Path to the MATLAB output folder containing processed data
        """
        self.matlab_output_folder: Path = Path(matlab_output_folder)

        if not self.matlab_output_folder.exists():
            raise FileNotFoundError(f"MATLAB output folder not found: {matlab_output_folder}")

        # Cache for loaded data to avoid repeated file reads
        self._processing_summary_cache: pd.DataFrame | None = None
        self._discrete_variables_cache: pd.DataFrame | None = None

    def get_processing_summary(self, refresh_cache: bool = False) -> pd.DataFrame:
        """
        Load the processing summary containing status for all processed files.
        
        Args:
            refresh_cache: Whether to reload the data from file
            
        Returns:
            DataFrame with columns: FileIndex, ID, SubjectID, SessionID, 
                                  JsonFile, ProcessingStatus, ErrorMessage
        """
        if self._processing_summary_cache is None or refresh_cache:
            summary_file = self.matlab_output_folder / PROCESSING_SUMMARY_FILE_NAME
            if not summary_file.exists():
                raise FileNotFoundError(f"Processing summary file not found: {summary_file}")

            self._processing_summary_cache = pd.read_csv(summary_file)

        return self._processing_summary_cache.copy()

    def get_discrete_variables(self, refresh_cache: bool = False) -> pd.DataFrame:
        """
        Load the discrete variables data for all successfully processed sessions.
        
        Args:
            refresh_cache: Whether to reload the data from file
            
        Returns:
            DataFrame with discrete gait variables for each session
        """
        if self._discrete_variables_cache is None or refresh_cache:
            discrete_file = self.matlab_output_folder / DISCRETE_VARIABLES_FILE_NAME
            if not discrete_file.exists():
                raise FileNotFoundError(f"Discrete variables file not found: {discrete_file}")

            self._discrete_variables_cache = pd.read_csv(discrete_file)

        return self._discrete_variables_cache.copy()

    def get_available_sessions(self) -> List[str]:
        """
        Get list of all available session IDs that have processed data.

        NOTE: Looks at the folder structure to find all available sessions.
        It is prefered to use get_successful_sessions() instead.
        
        Returns:
            List of session IDs (format: {subject_id}_{session_id})
        """
        sessions = []
        for item in self.matlab_output_folder.iterdir():
            if item.is_dir() and not item.name.startswith('.'):
                # Check if it has the expected structure (inputs and results folders)
                if (item / INPUTS_FOLDER_NAME).exists() and (item / RESULTS_FOLDER_NAME).exists():
                    sessions.append(item.name)

        return sorted(sessions)

    def get_successful_sessions(self) -> List[str]:
        """
        Get list of session IDs that were successfully processed.
        
        Returns:
            List of successfully processed session IDs
        """
        summary = self.get_processing_summary()
        successful = summary[summary['ProcessingStatus'] == 'Success']
        return successful['ID'].tolist()

    def get_failed_sessions(self) -> List[Tuple[str, str]]:
        """
        Get list of session IDs that failed processing along with error messages.
        
        Returns:
            List of tuples (session_id, error_message)
        """
        summary = self.get_processing_summary()
        failed = summary[summary['ProcessingStatus'] == 'Error']
        return list(zip(failed['ID'].tolist(), failed['ErrorMessage'].tolist()))

    def get_session_folder(self, session_id: str) -> Path:
        """
        Get the path to a specific session's data folder.
        
        Args:
            session_id: Session identifier (format: {subject_id}_{session_id})
            
        Returns:
            Path to the session folder
            
        Raises:
            FileNotFoundError: If session folder doesn't exist
        """
        session_folder = self.matlab_output_folder / session_id
        if not session_folder.exists():
            raise FileNotFoundError(f"Session folder not found: {session_folder}")

        return session_folder

    def get_joint_angles(self, session_id: str, joint: str, 
                        normalized: bool = False) -> pd.DataFrame:
        """
        Load joint angle data for a specific session and joint.
        
        Args:
            session_id: Session identifier
            joint: Joint name (e.g., 'L_ankle', 'R_knee', 'pelvis')
            normalized: Whether to load normalized (% gait cycle) or raw time series data
            
        Returns:
            DataFrame with angle data:
            - If normalized=False: columns are TimeIndex, X_deg, Y_deg, Z_deg
            - If normalized=True: columns are PercentGaitCycle, X_deg, Y_deg, Z_deg
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME

        if normalized:
            filename = JOINT_NORM_ANGLES_TEMPLATE.format(joint=joint)
        else:
            filename = JOINT_ANGLES_TEMPLATE.format(joint=joint)

        file_path = results_folder / filename
        if not file_path.exists():
            raise FileNotFoundError(f"Joint angles file not found: {file_path}")

        return pd.read_csv(file_path)

    def get_joint_velocities(self, session_id: str, joint: str, 
                           normalized: bool = False) -> pd.DataFrame:
        """
        Load joint velocity data for a specific session and joint.
        
        Args:
            session_id: Session identifier
            joint: Joint name (e.g., 'L_ankle', 'R_knee', 'pelvis')
            normalized: Whether to load normalized (% gait cycle) or raw time series data
            
        Returns:
            DataFrame with velocity data:
            - If normalized=False: columns are TimeIndex, X_deg_per_s, Y_deg_per_s, Z_deg_per_s
            - If normalized=True: columns are PercentGaitCycle, X_deg_per_s, Y_deg_per_s, Z_deg_per_s
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME

        if normalized:
            filename = JOINT_NORM_VELOCITIES_TEMPLATE.format(joint=joint)
        else:
            filename = JOINT_VELOCITIES_TEMPLATE.format(joint=joint)

        file_path = results_folder / filename
        if not file_path.exists():
            raise FileNotFoundError(f"Joint velocities file not found: {file_path}")

        return pd.read_csv(file_path)

    def get_all_joint_angles(self, session_id: str, normalized: bool = False) -> Dict[str, pd.DataFrame]:
        """
        Load angle data for all joints in a session.
        
        Args:
            session_id: Session identifier
            normalized: Whether to load normalized or raw data
            
        Returns:
            Dictionary mapping joint names to their angle DataFrames
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME

        joint_data = {}
        suffix = NORM_ANGLES_SUFFIX if normalized else ANGLES_SUFFIX

        for file_path in results_folder.glob(f"*{ANGLES_SUFFIX}"):
            # Handle both _angles.csv and _norm_angles.csv
            file_name = file_path.name
            if file_name.endswith(NORM_ANGLES_SUFFIX):
                if normalized:
                    joint_name = file_name.replace(NORM_ANGLES_SUFFIX, "")
                    joint_data[joint_name] = pd.read_csv(file_path)
            elif file_name.endswith(ANGLES_SUFFIX):
                if not normalized:
                    joint_name = file_name.replace(ANGLES_SUFFIX, "")
                    joint_data[joint_name] = pd.read_csv(file_path)

        return joint_data

    def get_all_joint_velocities(self, session_id: str, normalized: bool = False) -> Dict[str, pd.DataFrame]:
        """
        Load velocity data for all joints in a session.
        
        Args:
            session_id: Session identifier
            normalized: Whether to load normalized or raw data
            
        Returns:
            Dictionary mapping joint names to their velocity DataFrames
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME

        joint_data = {}
        suffix = NORM_VELOCITIES_SUFFIX if normalized else VELOCITIES_SUFFIX

        for file_path in results_folder.glob(f"*{VELOCITIES_SUFFIX}"):
            # Handle both _velocities.csv and _norm_velocities.csv
            file_name = file_path.name
            if file_name.endswith(NORM_VELOCITIES_SUFFIX):
                if normalized:
                    joint_name = file_name.replace(NORM_VELOCITIES_SUFFIX, "")
                    joint_data[joint_name] = pd.read_csv(file_path)
            elif file_name.endswith(VELOCITIES_SUFFIX):
                if not normalized:
                    joint_name = file_name.replace(VELOCITIES_SUFFIX, "")
                    joint_data[joint_name] = pd.read_csv(file_path)

        return joint_data

    def get_gait_events(self, session_id: str) -> pd.DataFrame:
        """
        Load gait cycle events for a session.
        
        Args:
            session_id: Session identifier
            
        Returns:
            DataFrame with gait events (EventNumber, EventIndex)
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME
        events_file = results_folder / GAIT_CYCLE_EVENTS_FILE_NAME

        if not events_file.exists():
            raise FileNotFoundError(f"Gait events file not found: {events_file}")

        return pd.read_csv(events_file)

    def get_joint_centers(self, session_id: str) -> pd.DataFrame:
        """
        Load joint center coordinates for a session.
        
        Args:
            session_id: Session identifier
            
        Returns:
            DataFrame with joint centers (Joint, X_coord, Y_coord, Z_coord)
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME
        centers_file = results_folder / JOINT_CENTERS_FILE_NAME

        if not centers_file.exists():
            raise FileNotFoundError(f"Joint centers file not found: {centers_file}")

        return pd.read_csv(centers_file)

    def get_marker_data(self, session_id: str, marker: str) -> pd.DataFrame:
        """
        Load marker trajectory data for a specific marker.
        
        Args:
            session_id: Session identifier
            marker: Marker name (e.g., 'L_foot_1', 'R_thigh_2', 'pelvis_3')
            
        Returns:
            DataFrame with marker trajectory (TimeIndex, X_coord, Y_coord, Z_coord)
        """
        session_folder = self.get_session_folder(session_id)
        inputs_folder = session_folder / INPUTS_FOLDER_NAME
        marker_file = inputs_folder / MARKER_DATA_TEMPLATE.format(marker=marker)

        if not marker_file.exists():
            raise FileNotFoundError(f"Marker data file not found: {marker_file}")

        return pd.read_csv(marker_file)

    def get_available_joints(self, session_id: str) -> List[str]:
        """
        Get list of available joints for a session.
        
        Args:
            session_id: Session identifier
            
        Returns:
            List of joint names available in this session
        """
        session_folder = self.get_session_folder(session_id)
        results_folder = session_folder / RESULTS_FOLDER_NAME

        joints = set()
        for file_path in results_folder.glob(f"*{ANGLES_SUFFIX}"):
            # Handle both _angles.csv and _norm_angles.csv
            file_name = file_path.name
            if file_name.endswith(NORM_ANGLES_SUFFIX):
                joint_name = file_name.replace(NORM_ANGLES_SUFFIX, "")
            elif file_name.endswith(ANGLES_SUFFIX):
                joint_name = file_name.replace(ANGLES_SUFFIX, "")
            else:
                continue  # Skip files that don't match expected pattern
            joints.add(joint_name)

        return sorted(list(joints))

    def get_available_markers(self, session_id: str) -> List[str]:
        """
        Get list of available markers for a session.
        
        Args:
            session_id: Session identifier
            
        Returns:
            List of marker names available in this session
        """
        session_folder = self.get_session_folder(session_id)
        inputs_folder = session_folder / INPUTS_FOLDER_NAME

        markers = set()
        for file_path in inputs_folder.glob(f"*{MARKER_DATA_SUFFIX}"):
            marker_name = file_path.name.replace(MARKER_DATA_SUFFIX, "")
            markers.add(marker_name)

        return sorted(markers)

    def get_session_info(self, session_id: str) -> Dict:
        """
        Get comprehensive information about a session.
        
        Args:
            session_id: Session identifier
            
        Returns:
            Dictionary with session information including available data types
        """
        session_folder = self.get_session_folder(session_id)

        info = {
            'session_id': session_id,
            'folder_path': str(session_folder),
            'available_joints': self.get_available_joints(session_id),
            'available_markers': self.get_available_markers(session_id),
            'has_gait_events': (session_folder / RESULTS_FOLDER_NAME / GAIT_CYCLE_EVENTS_FILE_NAME).exists(),
            'has_joint_centers': (session_folder / RESULTS_FOLDER_NAME / JOINT_CENTERS_FILE_NAME).exists(),
            'has_matlab_results': (session_folder / f"{session_id}{MATLAB_RESULTS_FILE_SUFFIX}").exists()
        }

        # Add processing status if available
        try:
            summary = self.get_processing_summary()
            session_info = summary[summary['ID'] == session_id]
            if not session_info.empty:
                info['processing_status'] = session_info.iloc[0]['ProcessingStatus']
                info['subject_id'] = session_info.iloc[0]['SubjectID']
                info['session_id_only'] = session_info.iloc[0]['SessionID']
        except Exception as e:
            warnings.warn(f"Could not load processing summary: {e}")

        return info
