import os
import json
from collections import defaultdict
from typing import Dict, Tuple, Any, List
import pandas as pd
from pydantic import BaseModel
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline


class MarkerPoint(BaseModel):
    x: float
    y: float
    z: float

    @classmethod
    def from_coordinates_list(cls, lst: list) -> "MarkerPoint":
        if len(lst) != 3:
            raise ValueError(f"Expected 3D coordinates, got {len(lst)}")
        return cls(x=lst[0], y=lst[1], z=lst[2])


class SessionData(BaseModel):
    session_id: str
    subject_id: int
    session_hz: int
    desc_variables: dict
    marker_center_data: dict
    marker_data: dict


def get_dv_var_name(side, orig_name) -> str:
    return side + "_" + str.lower(orig_name)


def get_marker_center_var_name(group, orig_name) -> str:
    return group + "_" + str.lower(orig_name)


def get_marker_var_name(orig_name) -> str:
    return str.lower(orig_name)


def process_row(row: Tuple[int, Dict], source_data_folder: str) -> SessionData:
    idx, session = row
    row_id = session['id']
    subject_id = session['sub_id']
    relative_session_path = session['session_file_path']

    json_session = json.load(open(os.path.join(source_data_folder, relative_session_path)))
    frequency_hz = json_session['hz_r']

    # Extract Descriptive Variable data
    dv_data = {}
    dv_data['id'] = row_id
    dv_data['subject_id'] = subject_id
    dv_data['session_file_path'] = relative_session_path

    dv_r = json_session['dv_r']
    variables = {
        'l': dv_r['left'],
        'r': dv_r['right']
    }
    
    for side, data in variables.items():
        for name, value in data.items():
            variable_name = get_dv_var_name(side, name)
            dv_data[variable_name] = value
    
    # Extract Marker center data
    marker_center_data = defaultdict(list)
    marker_center_data['id'] = row_id
    marker_center_data['subject_id'] = subject_id
    marker_center_data['session_file_path'] = relative_session_path

    marker_vars = {
        "indiv": json_session['joints'],
        "cluster": json_session['neutral']
    }
    
    for group, data in marker_vars.items():
        for keypoint, coordinates in data.items():
            marker = MarkerPoint.from_coordinates_list(coordinates)
            variable_prefix = get_marker_center_var_name(group, keypoint)
            marker_center_data[variable_prefix + "_x"] = marker.x
            marker_center_data[variable_prefix + "_y"] = marker.y
            marker_center_data[variable_prefix + "_z"] = marker.z
    
    # Extract Marker data
    marker_data = defaultdict(list)
    marker_vars = json_session['running']

    is_first_keypoint = True
    for keypoint, data in marker_vars.items():
        for coordinates in data:
            marker = MarkerPoint.from_coordinates_list(coordinates)
            variable_prefix = get_marker_var_name(keypoint)
            if is_first_keypoint:
                marker_data['id'].append(row_id)
                marker_data['subject_id'].append(subject_id)
                marker_data['session_file_path'].append(relative_session_path)
            marker_data[variable_prefix + "_x"].append(marker.x)
            marker_data[variable_prefix + "_y"].append(marker.y)
            marker_data[variable_prefix + "_z"].append(marker.z)
        is_first_keypoint = False

    return SessionData(
        session_id=row_id, 
        subject_id=subject_id, 
        session_hz=frequency_hz, 
        desc_variables=dv_data, 
        marker_center_data=marker_center_data, 
        marker_data=marker_data
    )


def preprocess_features(
        X: pd.DataFrame, Y:
        pd.Series,
        feature_categorical_columns: List[str] = None,
        num_fill_value: float = None,
        cat_drop: str = "if_binary",
        return_scaler: bool = False
    ) -> pd.DataFrame | Tuple[pd.DataFrame, StandardScaler]:
    """
    Preprocess features by handling missing values and applying scaling/encoding.
    
    This function performs a two-step preprocessing:
    1. Imputation: Fill missing values
    2. Preprocessing: Scale numerical features and one-hot encode categorical features

    NOTE:
        - In cagegorical data None is considered as missing value.
        - If num_fill_value is None, the median will be used for numerical features.
        - The column generated by the one-hot encoder for missing categorical data will be dropped.

    
    Args:
        X: Feature dataframe
        Y: Target series  
        feature_categorical_columns: List of categorical column names
        
    Returns:
        Preprocessed feature dataframe with imputed values, scaled numerical features,
        and one-hot encoded categorical features
    """
    if feature_categorical_columns is not None:
        cat_cols = feature_categorical_columns
    else:
        cat_cols = [c for c in X.columns if X[c].dtype == 'object']

    num_cols = [c for c in X.columns if c not in cat_cols]

    imputer = ColumnTransformer(
        transformers=[
            ('impute_num', SimpleImputer(strategy='median', copy=True, fill_value=num_fill_value), num_cols),
            ('impute_cat', SimpleImputer(strategy='constant', fill_value="unknown", copy=True), cat_cols)
        ],
        remainder='passthrough',
        verbose_feature_names_out=False
    )

    X_imputed = imputer.fit_transform(X, Y)
    X_imputed_df = pd.DataFrame(X_imputed, columns=imputer.get_feature_names_out(), index=X.index)

    # Step 2: Preprocessing (scaling and encoding)
    preprocessing = ColumnTransformer(
        transformers=[
            ('scale_num', StandardScaler(), num_cols),
            ('encode_cat', OneHotEncoder(drop=cat_drop, handle_unknown="ignore"), cat_cols)
        ],
        remainder='passthrough',
        verbose_feature_names_out=False
    )

    X_prep = preprocessing.fit_transform(X_imputed_df, Y)
    X_combined = pd.DataFrame(X_prep, columns=preprocessing.get_feature_names_out(), index=X.index)
    
    # Remove the 'unknown' columns that were added during imputation
    unknown_cols_to_drop = [col + "_unknown" for col in cat_cols if col + "_unknown" in X_combined.columns]
    X_combined = X_combined.drop(columns=unknown_cols_to_drop)
    
    if return_scaler:
        return X_combined, preprocessing.named_transformers_['scale_num']
    else:
        return X_combined


class ResultModel(BaseModel):
    model_name: str
    model_file: str
    test_accuracy: float
    test_precision: float
    test_recall: float
    test_f1: float
    test_roc_auc: float
    y_pred: Any
    y_pred_proba: Any
    best_parameters: Any
    best_score: float

    class Config:
        arbitrary_types_allowed = True
        json_encoders = {
            # Handles numpy types and arrays
            # (np types are not imported here, but pydantic will use .tolist() if present)
        }

class ResultsModel(BaseModel):
    results: List[ResultModel]